name: Hello World Workflow

on: [push]

jobs:
  hello_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display Hello World 1
        run: echo "✅ Hello World 1"
        
  hello_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display Hello World 2
        run: echo "✅ Hello World 2"